// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.3
// source: tao.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Otype string          `protobuf:"bytes,2,opt,name=otype,proto3" json:"otype,omitempty"`
	Data  []*KeyValuePair `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ObjectAddRequest) Reset() {
	*x = ObjectAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tao_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectAddRequest) ProtoMessage() {}

func (x *ObjectAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tao_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectAddRequest.ProtoReflect.Descriptor instead.
func (*ObjectAddRequest) Descriptor() ([]byte, []int) {
	return file_tao_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectAddRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectAddRequest) GetOtype() string {
	if x != nil {
		return x.Otype
	}
	return ""
}

func (x *ObjectAddRequest) GetData() []*KeyValuePair {
	if x != nil {
		return x.Data
	}
	return nil
}

type GenericOkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenericOkResponse) Reset() {
	*x = GenericOkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tao_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericOkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericOkResponse) ProtoMessage() {}

func (x *GenericOkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tao_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericOkResponse.ProtoReflect.Descriptor instead.
func (*GenericOkResponse) Descriptor() ([]byte, []int) {
	return file_tao_proto_rawDescGZIP(), []int{1}
}

type AssocAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id1   string `protobuf:"bytes,1,opt,name=id1,proto3" json:"id1,omitempty"`
	Atype string `protobuf:"bytes,2,opt,name=atype,proto3" json:"atype,omitempty"`
	Id2   string `protobuf:"bytes,3,opt,name=id2,proto3" json:"id2,omitempty"`
}

func (x *AssocAddRequest) Reset() {
	*x = AssocAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tao_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssocAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssocAddRequest) ProtoMessage() {}

func (x *AssocAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tao_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssocAddRequest.ProtoReflect.Descriptor instead.
func (*AssocAddRequest) Descriptor() ([]byte, []int) {
	return file_tao_proto_rawDescGZIP(), []int{2}
}

func (x *AssocAddRequest) GetId1() string {
	if x != nil {
		return x.Id1
	}
	return ""
}

func (x *AssocAddRequest) GetAtype() string {
	if x != nil {
		return x.Atype
	}
	return ""
}

func (x *AssocAddRequest) GetId2() string {
	if x != nil {
		return x.Id2
	}
	return ""
}

type AssocDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id1   string `protobuf:"bytes,1,opt,name=id1,proto3" json:"id1,omitempty"`
	Atype string `protobuf:"bytes,2,opt,name=atype,proto3" json:"atype,omitempty"`
	Id2   string `protobuf:"bytes,3,opt,name=id2,proto3" json:"id2,omitempty"`
}

func (x *AssocDeleteRequest) Reset() {
	*x = AssocDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tao_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssocDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssocDeleteRequest) ProtoMessage() {}

func (x *AssocDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tao_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssocDeleteRequest.ProtoReflect.Descriptor instead.
func (*AssocDeleteRequest) Descriptor() ([]byte, []int) {
	return file_tao_proto_rawDescGZIP(), []int{3}
}

func (x *AssocDeleteRequest) GetId1() string {
	if x != nil {
		return x.Id1
	}
	return ""
}

func (x *AssocDeleteRequest) GetAtype() string {
	if x != nil {
		return x.Atype
	}
	return ""
}

func (x *AssocDeleteRequest) GetId2() string {
	if x != nil {
		return x.Id2
	}
	return ""
}

type AssocChangeType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id1     string `protobuf:"bytes,1,opt,name=id1,proto3" json:"id1,omitempty"`
	Atype   string `protobuf:"bytes,2,opt,name=atype,proto3" json:"atype,omitempty"`
	Id2     string `protobuf:"bytes,3,opt,name=id2,proto3" json:"id2,omitempty"`
	NewType string `protobuf:"bytes,4,opt,name=newType,proto3" json:"newType,omitempty"`
}

func (x *AssocChangeType) Reset() {
	*x = AssocChangeType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tao_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssocChangeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssocChangeType) ProtoMessage() {}

func (x *AssocChangeType) ProtoReflect() protoreflect.Message {
	mi := &file_tao_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssocChangeType.ProtoReflect.Descriptor instead.
func (*AssocChangeType) Descriptor() ([]byte, []int) {
	return file_tao_proto_rawDescGZIP(), []int{4}
}

func (x *AssocChangeType) GetId1() string {
	if x != nil {
		return x.Id1
	}
	return ""
}

func (x *AssocChangeType) GetAtype() string {
	if x != nil {
		return x.Atype
	}
	return ""
}

func (x *AssocChangeType) GetId2() string {
	if x != nil {
		return x.Id2
	}
	return ""
}

func (x *AssocChangeType) GetNewType() string {
	if x != nil {
		return x.NewType
	}
	return ""
}

type AssocGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id1   string   `protobuf:"bytes,1,opt,name=id1,proto3" json:"id1,omitempty"`
	Atype string   `protobuf:"bytes,2,opt,name=atype,proto3" json:"atype,omitempty"`
	Id2   []string `protobuf:"bytes,3,rep,name=id2,proto3" json:"id2,omitempty"`
	Low   *string  `protobuf:"bytes,4,opt,name=low,proto3,oneof" json:"low,omitempty"`
	High  *string  `protobuf:"bytes,5,opt,name=high,proto3,oneof" json:"high,omitempty"`
}

func (x *AssocGetRequest) Reset() {
	*x = AssocGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tao_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssocGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssocGetRequest) ProtoMessage() {}

func (x *AssocGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tao_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssocGetRequest.ProtoReflect.Descriptor instead.
func (*AssocGetRequest) Descriptor() ([]byte, []int) {
	return file_tao_proto_rawDescGZIP(), []int{5}
}

func (x *AssocGetRequest) GetId1() string {
	if x != nil {
		return x.Id1
	}
	return ""
}

func (x *AssocGetRequest) GetAtype() string {
	if x != nil {
		return x.Atype
	}
	return ""
}

func (x *AssocGetRequest) GetId2() []string {
	if x != nil {
		return x.Id2
	}
	return nil
}

func (x *AssocGetRequest) GetLow() string {
	if x != nil && x.Low != nil {
		return *x.Low
	}
	return ""
}

func (x *AssocGetRequest) GetHigh() string {
	if x != nil && x.High != nil {
		return *x.High
	}
	return ""
}

type KeyValuePair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tao_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_tao_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_tao_proto_rawDescGZIP(), []int{6}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items []*KeyValuePair `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tao_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_tao_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_tao_proto_rawDescGZIP(), []int{7}
}

func (x *Object) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Object) GetItems() []*KeyValuePair {
	if x != nil {
		return x.Items
	}
	return nil
}

type AssocGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects []*Object `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *AssocGetResponse) Reset() {
	*x = AssocGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tao_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssocGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssocGetResponse) ProtoMessage() {}

func (x *AssocGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tao_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssocGetResponse.ProtoReflect.Descriptor instead.
func (*AssocGetResponse) Descriptor() ([]byte, []int) {
	return file_tao_proto_rawDescGZIP(), []int{8}
}

func (x *AssocGetResponse) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type BulkAssocAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req []*AssocAddRequest `protobuf:"bytes,1,rep,name=req,proto3" json:"req,omitempty"`
}

func (x *BulkAssocAddRequest) Reset() {
	*x = BulkAssocAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tao_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkAssocAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkAssocAddRequest) ProtoMessage() {}

func (x *BulkAssocAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tao_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkAssocAddRequest.ProtoReflect.Descriptor instead.
func (*BulkAssocAddRequest) Descriptor() ([]byte, []int) {
	return file_tao_proto_rawDescGZIP(), []int{9}
}

func (x *BulkAssocAddRequest) GetReq() []*AssocAddRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type ObjectGetDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*KeyValuePair `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ObjectGetDataRequest) Reset() {
	*x = ObjectGetDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tao_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectGetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectGetDataRequest) ProtoMessage() {}

func (x *ObjectGetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tao_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectGetDataRequest.ProtoReflect.Descriptor instead.
func (*ObjectGetDataRequest) Descriptor() ([]byte, []int) {
	return file_tao_proto_rawDescGZIP(), []int{10}
}

func (x *ObjectGetDataRequest) GetData() []*KeyValuePair {
	if x != nil {
		return x.Data
	}
	return nil
}

type ObjectGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Otype string                `protobuf:"bytes,1,opt,name=otype,proto3" json:"otype,omitempty"`
	Limit int64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Data  *ObjectGetDataRequest `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *ObjectGetRequest) Reset() {
	*x = ObjectGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tao_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectGetRequest) ProtoMessage() {}

func (x *ObjectGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tao_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectGetRequest.ProtoReflect.Descriptor instead.
func (*ObjectGetRequest) Descriptor() ([]byte, []int) {
	return file_tao_proto_rawDescGZIP(), []int{11}
}

func (x *ObjectGetRequest) GetOtype() string {
	if x != nil {
		return x.Otype
	}
	return ""
}

func (x *ObjectGetRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ObjectGetRequest) GetData() *ObjectGetDataRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

type AssocRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id1   string `protobuf:"bytes,1,opt,name=id1,proto3" json:"id1,omitempty"`
	Atype string `protobuf:"bytes,2,opt,name=atype,proto3" json:"atype,omitempty"`
	Pos   int64  `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Limit int64  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *AssocRangeRequest) Reset() {
	*x = AssocRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tao_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssocRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssocRangeRequest) ProtoMessage() {}

func (x *AssocRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tao_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssocRangeRequest.ProtoReflect.Descriptor instead.
func (*AssocRangeRequest) Descriptor() ([]byte, []int) {
	return file_tao_proto_rawDescGZIP(), []int{12}
}

func (x *AssocRangeRequest) GetId1() string {
	if x != nil {
		return x.Id1
	}
	return ""
}

func (x *AssocRangeRequest) GetAtype() string {
	if x != nil {
		return x.Atype
	}
	return ""
}

func (x *AssocRangeRequest) GetPos() int64 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *AssocRangeRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_tao_proto protoreflect.FileDescriptor

var file_tao_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x61, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x61, 0x6f,
	0x22, 0x5f, 0x0a, 0x10, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x61, 0x6f, 0x2e, 0x4b,
	0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x4f, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4b, 0x0a, 0x0f, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x69, 0x64, 0x32, 0x22, 0x4e, 0x0a, 0x12, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x69, 0x64, 0x32, 0x22, 0x65, 0x0a, 0x0f, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x69, 0x64, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x32,
	0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x54, 0x79, 0x70, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x0f, 0x41,
	0x73, 0x73, 0x6f, 0x63, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x69, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x31,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x61, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x32, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x32, 0x12, 0x15, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x88, 0x01, 0x01, 0x12,
	0x17, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x04, 0x68, 0x69, 0x67, 0x68, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6c, 0x6f, 0x77,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x68, 0x69, 0x67, 0x68, 0x22, 0x36, 0x0a, 0x0c, 0x4b, 0x65, 0x79,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x41, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x61, 0x6f,
	0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x39, 0x0a, 0x10, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x61, 0x6f, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22,
	0x3d, 0x0a, 0x13, 0x42, 0x75, 0x6c, 0x6b, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x61, 0x6f, 0x2e, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x3d,
	0x0a, 0x14, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x61, 0x6f, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7b, 0x0a,
	0x10, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x32, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x61,
	0x6f, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01,
	0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x63, 0x0a, 0x11, 0x41, 0x73,
	0x73, 0x6f, 0x63, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64,
	0x31, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x61, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x32,
	0xf5, 0x02, 0x0a, 0x0a, 0x54, 0x61, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a,
	0x0a, 0x09, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x64, 0x64, 0x12, 0x15, 0x2e, 0x74, 0x61,
	0x6f, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x74, 0x61, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63,
	0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x09, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x47, 0x65, 0x74, 0x12, 0x15, 0x2e, 0x74, 0x61, 0x6f, 0x2e, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x74, 0x61, 0x6f, 0x2e, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x41, 0x64,
	0x64, 0x12, 0x14, 0x2e, 0x74, 0x61, 0x6f, 0x2e, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x74, 0x61, 0x6f, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x69, 0x63, 0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x37, 0x0a, 0x08, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x47, 0x65, 0x74, 0x12, 0x14, 0x2e, 0x74, 0x61,
	0x6f, 0x2e, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x74, 0x61, 0x6f, 0x2e, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x41, 0x73, 0x73, 0x6f,
	0x63, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x2e, 0x74, 0x61, 0x6f, 0x2e, 0x41, 0x73, 0x73,
	0x6f, 0x63, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x74, 0x61, 0x6f, 0x2e, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x42, 0x75, 0x6c, 0x6b, 0x41, 0x73, 0x73,
	0x6f, 0x63, 0x41, 0x64, 0x64, 0x12, 0x18, 0x2e, 0x74, 0x61, 0x6f, 0x2e, 0x42, 0x75, 0x6c, 0x6b,
	0x41, 0x73, 0x73, 0x6f, 0x63, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x74, 0x61, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x4f, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x62, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x65, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x61, 0x6f, 0x2d, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x2f, 0x74, 0x61, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_tao_proto_rawDescOnce sync.Once
	file_tao_proto_rawDescData = file_tao_proto_rawDesc
)

func file_tao_proto_rawDescGZIP() []byte {
	file_tao_proto_rawDescOnce.Do(func() {
		file_tao_proto_rawDescData = protoimpl.X.CompressGZIP(file_tao_proto_rawDescData)
	})
	return file_tao_proto_rawDescData
}

var file_tao_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_tao_proto_goTypes = []interface{}{
	(*ObjectAddRequest)(nil),     // 0: tao.ObjectAddRequest
	(*GenericOkResponse)(nil),    // 1: tao.GenericOkResponse
	(*AssocAddRequest)(nil),      // 2: tao.AssocAddRequest
	(*AssocDeleteRequest)(nil),   // 3: tao.AssocDeleteRequest
	(*AssocChangeType)(nil),      // 4: tao.AssocChangeType
	(*AssocGetRequest)(nil),      // 5: tao.AssocGetRequest
	(*KeyValuePair)(nil),         // 6: tao.KeyValuePair
	(*Object)(nil),               // 7: tao.Object
	(*AssocGetResponse)(nil),     // 8: tao.AssocGetResponse
	(*BulkAssocAddRequest)(nil),  // 9: tao.BulkAssocAddRequest
	(*ObjectGetDataRequest)(nil), // 10: tao.ObjectGetDataRequest
	(*ObjectGetRequest)(nil),     // 11: tao.ObjectGetRequest
	(*AssocRangeRequest)(nil),    // 12: tao.AssocRangeRequest
}
var file_tao_proto_depIdxs = []int32{
	6,  // 0: tao.ObjectAddRequest.data:type_name -> tao.KeyValuePair
	6,  // 1: tao.Object.items:type_name -> tao.KeyValuePair
	7,  // 2: tao.AssocGetResponse.objects:type_name -> tao.Object
	2,  // 3: tao.BulkAssocAddRequest.req:type_name -> tao.AssocAddRequest
	6,  // 4: tao.ObjectGetDataRequest.data:type_name -> tao.KeyValuePair
	10, // 5: tao.ObjectGetRequest.data:type_name -> tao.ObjectGetDataRequest
	0,  // 6: tao.TaoService.ObjectAdd:input_type -> tao.ObjectAddRequest
	11, // 7: tao.TaoService.ObjectGet:input_type -> tao.ObjectGetRequest
	2,  // 8: tao.TaoService.AssocAdd:input_type -> tao.AssocAddRequest
	5,  // 9: tao.TaoService.AssocGet:input_type -> tao.AssocGetRequest
	12, // 10: tao.TaoService.AssocRange:input_type -> tao.AssocRangeRequest
	9,  // 11: tao.TaoService.BulkAssocAdd:input_type -> tao.BulkAssocAddRequest
	1,  // 12: tao.TaoService.ObjectAdd:output_type -> tao.GenericOkResponse
	8,  // 13: tao.TaoService.ObjectGet:output_type -> tao.AssocGetResponse
	1,  // 14: tao.TaoService.AssocAdd:output_type -> tao.GenericOkResponse
	8,  // 15: tao.TaoService.AssocGet:output_type -> tao.AssocGetResponse
	8,  // 16: tao.TaoService.AssocRange:output_type -> tao.AssocGetResponse
	1,  // 17: tao.TaoService.BulkAssocAdd:output_type -> tao.GenericOkResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_tao_proto_init() }
func file_tao_proto_init() {
	if File_tao_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tao_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tao_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericOkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tao_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssocAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tao_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssocDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tao_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssocChangeType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tao_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssocGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tao_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValuePair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tao_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tao_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssocGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tao_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkAssocAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tao_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectGetDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tao_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tao_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssocRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tao_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_tao_proto_msgTypes[11].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tao_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tao_proto_goTypes,
		DependencyIndexes: file_tao_proto_depIdxs,
		MessageInfos:      file_tao_proto_msgTypes,
	}.Build()
	File_tao_proto = out.File
	file_tao_proto_rawDesc = nil
	file_tao_proto_goTypes = nil
	file_tao_proto_depIdxs = nil
}
